Upgrade to Aave v3.0.2
marsfoundation/sparklend pull request #29
Opened 2023-06-20 17:18 UTC by hexonaut

This PR adds a deploy script for the Pool implementation and upgrades Aave to V3.0.2. This is the first step before running an upgrade spell.

Goerli Deploy: [0x38C45a91f2b69B25e115238c8E82548fB20131Be](https://goerli.etherscan.io/address/0x38C45a91f2b69B25e115238c8E82548fB20131Be#code)

Will deploy to mainnet when this looks good.

2023-07-10 11:58 UTC, hexonaut commented
Please note this is blocked on https://github.com/foundry-rs/foundry/issues/5330

2023-07-15 04:10 UTC, lucas-manuel requested changes
Did the following:
- Reviewed script
- Reviewed tests
- Reviewed AAVE submodule update diff for smart contracts, LGTM
- Ran a local sourcify and ran validation script successfully.

LGTM, just two small comments left and a question: Why do we have to change the REVISION value in Pool.sol to get the verification to work?

2023-07-15 09:16 UTC, hexonaut commented on README.md
> +Run `./validate-deploy.sh path/to/broadcast.json` (Be sure to `forge build` with proper settings first)
Yeah this is fixed in the GC one as discussed. Reads from the file instead of `cast`.

2023-07-15 09:16 UTC, lucas-manuel approved these changes
Can merge once CI passes

2023-07-15 09:23 UTC, merged