[SC-161] Add irs that target dynamic rates for kink and base
marsfoundation/sparklend pull request #36
Opened 2023-10-05 07:27 UTC by hexonaut

Reads a dynamic rate to target instead of hard coded values. There are a few uses for this:

Kinked version: Will be used for USDC/USDT markets on mainnet to target just under the DSR. Can also be used for ETH market if/when we get a good measure of APR for staked eth yield.

Base version: Targetting DAI market to be some spread above the DSR yield.

2023-10-27 14:18 UTC, lucas-manuel requested changes
Reviewed most of code, will review again after changes are made in relation to variableRateSpread discussion

2023-10-30 19:19 UTC, lucas-manuel requested changes
Quick formatting change while i audit test logic

2023-10-30 19:19 UTC, lucas-manuel commented on test/RateTargetKinkInterestRateStrategy.t.sol
> +    }
```suggestion
    function test_constructor() public {
        assertEq(address(interestStrategy.ADDRESSES_PROVIDER()), address(123));
        assertEq(address(interestStrategy.RATE_SOURCE()),        address(rateSource));

        assertEq(interestStrategy.OPTIMAL_USAGE_RATIO(),                   0);
        assertEq(interestStrategy.OPTIMAL_STABLE_TO_TOTAL_DEBT_RATIO(),    0);
        assertEq(interestStrategy.MAX_EXCESS_USAGE_RATIO(),                1e27);
        assertEq(interestStrategy.MAX_EXCESS_STABLE_TO_TOTAL_DEBT_RATIO(), 1e27);

        assertEq(interestStrategy.getVariableRateSlope1(),     0.035e27);
        assertEq(interestStrategy.getVariableRateSlope2(),     0.55e27);
        assertEq(interestStrategy.getStableRateSlope1(),       0);
        assertEq(interestStrategy.getStableRateSlope2(),       0);
        assertEq(interestStrategy.getStableRateExcessOffset(), 0);
        assertEq(interestStrategy.getBaseStableBorrowRate(),   0.035e27);
        assertEq(interestStrategy.getBaseVariableBorrowRate(), 0.01e27);
        assertEq(interestStrategy.getMaxVariableBorrowRate(),  0.595e27);

        assertEq(interestStrategyPositiveSpread.getVariableRateSlope1(),    0.045e27);
        assertEq(interestStrategyPositiveSpread.getVariableRateSlope2(),    0.55e27);
        assertEq(interestStrategyPositiveSpread.getMaxVariableBorrowRate(), 0.605e27);
    }

    function test_rateSource_change_kink_above_base() public {
        assertEq(interestStrategy.getVariableRateSlope1(),     0.035e27);
        assertEq(interestStrategy.getVariableRateSlope2(),     0.55e27);
        assertEq(interestStrategy.getBaseVariableBorrowRate(), 0.01e27);
        assertEq(interestStrategy.getMaxVariableBorrowRate(),  0.595e27);

        rateSource.setRate(0.07e27);

        assertEq(interestStrategy.getVariableRateSlope1(),     0.055e27);
        assertEq(interestStrategy.getVariableRateSlope2(),     0.55e27);
        assertEq(interestStrategy.getBaseVariableBorrowRate(), 0.01e27);
        assertEq(interestStrategy.getMaxVariableBorrowRate(),  0.615e27);
    }

    function test_rateSource_change_kink_below_base() public {
        assertEq(interestStrategy.getVariableRateSlope1(),     0.035e27);
        assertEq(interestStrategy.getVariableRateSlope2(),     0.55e27);
        assertEq(interestStrategy.getBaseVariableBorrowRate(), 0.01e27);
        assertEq(interestStrategy.getMaxVariableBorrowRate(),  0.595e27);

        rateSource.setRate(0.012e27);   // 1.2% - 0.5% = 0.7% < 1.0%

        assertEq(interestStrategy.getVariableRateSlope1(),     0);
        assertEq(interestStrategy.getVariableRateSlope2(),     0.55e27);
        assertEq(interestStrategy.getBaseVariableBorrowRate(), 0.01e27);
        assertEq(interestStrategy.getMaxVariableBorrowRate(),  0.56e27);
    }

    function test_rateSource_change_rate_below_base() public {
        assertEq(interestStrategy.getVariableRateSlope1(),     0.035e27);
        assertEq(interestStrategy.getVariableRateSlope2(),     0.55e27);
        assertEq(interestStrategy.getBaseVariableBorrowRate(), 0.01e27);
        assertEq(interestStrategy.getMaxVariableBorrowRate(),  0.595e27);

        rateSource.setRate(0);

        assertEq(interestStrategy.getVariableRateSlope1(),     0);
        assertEq(interestStrategy.getVariableRateSlope2(),     0.55e27);
        assertEq(interestStrategy.getBaseVariableBorrowRate(), 0.01e27);
        assertEq(interestStrategy.getMaxVariableBorrowRate(),  0.56e27);
    }
```

2023-10-30 19:19 UTC, lucas-manuel commented on test/RateTargetBaseInterestRateStrategy.t.sol
> +}
```suggestion
    function test_constructor() public {
        assertEq(address(interestStrategy.ADDRESSES_PROVIDER()), address(123));
        assertEq(address(interestStrategy.RATE_SOURCE()),        address(rateSource));

        assertEq(interestStrategy.OPTIMAL_USAGE_RATIO(),                   0);
        assertEq(interestStrategy.OPTIMAL_STABLE_TO_TOTAL_DEBT_RATIO(),    0);
        assertEq(interestStrategy.MAX_EXCESS_USAGE_RATIO(),                1e27);
        assertEq(interestStrategy.MAX_EXCESS_STABLE_TO_TOTAL_DEBT_RATIO(), 1e27);

        assertEq(interestStrategy.getVariableRateSlope1(),     0.01e27);
        assertEq(interestStrategy.getVariableRateSlope2(),     0.45e27);
        assertEq(interestStrategy.getStableRateSlope1(),       0);
        assertEq(interestStrategy.getStableRateSlope2(),       0);
        assertEq(interestStrategy.getStableRateExcessOffset(), 0);
        assertEq(interestStrategy.getBaseStableBorrowRate(),   0.01e27);
        assertEq(interestStrategy.getBaseVariableBorrowRate(), 0.055e27);
        assertEq(interestStrategy.getMaxVariableBorrowRate(),  0.515e27);
    }

    function test_rateSource_change() public {
        assertEq(interestStrategy.getVariableRateSlope1(),     0.01e27);
        assertEq(interestStrategy.getVariableRateSlope2(),     0.45e27);
        assertEq(interestStrategy.getBaseVariableBorrowRate(), 0.055e27);
        assertEq(interestStrategy.getMaxVariableBorrowRate(),  0.515e27);

        rateSource.setRate(0.07e27);

        assertEq(interestStrategy.getVariableRateSlope1(),     0.01e27);
        assertEq(interestStrategy.getVariableRateSlope2(),     0.45e27);
        assertEq(interestStrategy.getBaseVariableBorrowRate(), 0.075e27);
        assertEq(interestStrategy.getMaxVariableBorrowRate(),  0.535e27);
    }

}
```

2023-11-01 17:08 UTC, lucas-manuel approved these changes
Reviewed both against default strategy in lib, LGTM

2023-11-02 09:45 UTC, barrutko approved these changes

2023-11-02 11:20 UTC, merged